### PR TITLE
GazeMediaPlayer fix enter event issue

### LINKED ISSUE #1097: GazeMedia Player neeeds to have progressIndicator
**Describe the bug**
in the gazeMedia Player, each button is activated when gaze enter it what causes lot of midas touch problem related errors. we need to add a progressIndicator and start it on each GAZE_ENTERED  to avoid that 

**To Reproduce**
just try the gazeMedia Player and look at any button

**Expected behavior**
As in all the other games, the buttons of gazeMedia player should have a progressIndicator

### PR DESCRIPTION
**Pull request by kuhlkrein**
fix #1097 by adding progressIndicator + extracting lots of function to make the code easier to understand

### CODE REVIEW

File: gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayer.java [hunk 1]
```diff
@@ -183,26 +143,85 @@
...
+        return bwpi;
+    }
+
+    private StackPaneButton createButton(String text, double width, double height) {
+        StackPaneButton bwpi = new StackPaneButton(text);
+        bwpi.getButton().setMinWidth(width);
+        bwpi.getButton().setMinHeight(height);
+        bwpi.getButton().setPrefWidth(width);
+        bwpi.getButton().setPrefHeight(height);
+        return bwpi;
```
Comment (Tohaker) [inline gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayer.java]: Why doesn't this method just call the `createButton` method and add the text to the button? We should reduce code reuse wherever possible.

File: gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaButton.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+
+        this.addEventFilter(MouseEvent.MOUSE_ENTERED, enterEvent);
+
+        this.addEventFilter(MouseEvent.MOUSE_EXITED, exitEvent);
+
+        this.addEventFilter(GazeEvent.GAZE_ENTERED, enterEvent);
+
+        this.addEventFilter(GazeEvent.GAZE_EXITED, exitEvent);
+    }
+
```
Comment (Tohaker) [inline gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaButton.java]: Could we get some unit tests on this please?

Comment (kuhlkrein) [reply gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaButton.java]: yes done ;)

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+    @Test
+    void shouldCreateButtonOfGraphicStackPaneButton() {
+        try {
+            StackPaneButton stackPaneButton = GazeMediaPlayer.createGraphicStackPaneButton(500, 500, "src/test/resources/images/blue/blue.jpg");
+            ImageView graphicImageView = (ImageView) stackPaneButton.getButton().getGraphic();
+            assert stackPaneButton.getButton() != null;
+            assert graphicImageView.getImage().getUrl().contains("blue.jpg");
+        } catch (Exception ignored) {
+
+        }
```
Comment (kuhlkrein) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: I actually have a problem here @Tohaker , if I'm not adding this try catch I will have an IllegalArgumentException, I don't really get why...

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+    }
+
+    @Test
+    void shouldCreateButtonOfGraphicStackPaneButton() {
+        try {
+            StackPaneButton stackPaneButton = GazeMediaPlayer.createGraphicStackPaneButton(500, 500, "src/test/resources/images/blue/blue.jpg");
+            ImageView graphicImageView = (ImageView) stackPaneButton.getButton().getGraphic();
+            assert stackPaneButton.getButton() != null;
+            assert graphicImageView.getImage().getUrl().contains("blue.jpg");
+        } catch (Exception ignored) {
```
Comment (kuhlkrein) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: I just have a problem here @Tohaker , if I don't have this try catch then it gives me an IllegalArgumentException... I don't really get why..

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java (hunk 3 above)
Comment (Tohaker) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: You could just make the test throw the IllegalArgumentException, thats fine for Tests. The test runner will print the stacktrace if that test fails, so you can debug it later.

Comment (kuhlkrein) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: Ok, but then I have a :
> Task :gazeplay-games:test FAILED

net.gazeplay.games.mediaPlayer.GazeMediaPlayerTest > shouldCreateButtonOfGraphicStackPaneButton() FAILED
    java.lang.IllegalArgumentException at GazeMediaPlayerTest.java:38
        Caused by: java.lang.IllegalArgumentException at GazeMediaPlayerTest.java:38

24 tests completed, 1 failed

FAILURE: Build failed with an exception.

I don't understand where could be the "IllegalArgument"

Comment (kuhlkrein) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: Ok it was actually a question of path, I'm solving the conv

Comment (Tohaker) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: You shouldn't swallow exceptions in tests if the test fails without it. Either the test is not being created properly, or your tested method is not working.

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaButtonTest.java [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+
+    @BeforeEach
+    public void initMocks() {
+        MockitoAnnotations.initMocks(this);
+    }
+
+    @Test
+    void shouldNotSetUpGraphicForMediaButtonWithNoSetUpImageMethodCall() {
+        MediaButton mediaButton = new MediaButton(500, 500);
+        assert mediaButton.getButton().getGraphic() == null;
```
Comment (Tohaker) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaButtonTest.java]: You should use the `junit jupiter` methods of assertion here for better test logging. 
For example `assertNull()` here, and `assertTrue` and `assertFalse` in other tests.

Comment (kuhlkrein) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaButtonTest.java]: Oh ok I didn't know thank you

Comment (kuhlkrein) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaButtonTest.java]: done ;)

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java [hunk 6]
```diff
@@ -23,27 +24,27 @@ public void initMocks() {
     @Test
     void shouldCreateButtonOfSimpleStackPaneButton() {
         StackPaneButton stackPaneButton = GazeMediaPlayer.createSimpleStackPaneButton(500, 500);
-        assert stackPaneButton.getButton() != null;
+        Assert.assertNotNull(stackPaneButton.getButton());
```
Comment (Tohaker) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: Sorry, I wasn't clear in my last request. All other tests use `org.junit.jupiter.api.Assertions` rather than `org.junit.Assert`. Let's keep this uniform

Comment (kuhlkrein) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/GazeMediaPlayerTest.java]: No problem, done

**Comment by schwabdidier** [comment]
@kuhlkrein Now there is a conflict caused by other PR merging

**Comment by kuhlkrein** [comment]
Yes I will try to solve this, I had to rename this file, that's why

**Comment by kuhlkrein** [comment]
I have issues because I'm using net.gazeplay.games.colors.AbstractGazeIndicator; in package net.gazeplay.games.mediaPlayer but when I move AbstractGazeIndicator (named GazeIndicator in the gazeplay master branch) to another package then I have a conflict...

**Comment by kuhlkrein** [comment]
Should be fine now :)

File: gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java [hunk 7]
```diff
@@ -57,36 +60,58 @@
...
             return null;
         }
-        playing = (playing + 1) % mediaList.size();
-        return mediaList.get(playing);
+        playingMediaIndex.setValue((playingMediaIndex.getValue() - 1 + mediaList.size()) % mediaList.size());
+        return mediaList.get(playingMediaIndex.getValue());
     }
 
-    MediaFile prevPlayed() {
+    int getIndexofFirsToDisplay() {
```
Comment (YannRobert) [inline gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java]: ```getIndexOfFirstToDisplay```

**Comment by kuhlkrein** [comment]
@Tohaker I would have liked to implement some tests in this class for the part that is writing information in files, is there a way to create something like a "mock file" or "fake file" or should I create a temporary one for example?

**Comment by Tohaker** [comment]
If you take a look at the tests for FileUtils, you'll see the tests making "fake" files and then deleting them after the tests. You want to test with these real but unused files to get the best understanding of whether the code does what it should.

File: gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java [hunk 8]
```diff
@@ -51,72 +55,118 @@
...
+                    log.debug("Can't create file {}", playlistFile.getAbsoluteFile());
+                }
+            }
         }
     }
 
-    public MediaFile next() {
-        if (mediaList.isEmpty()) {
-            return null;
+    private IntegerProperty newIntegerProperty() {
```
Comment (Tohaker) [inline gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java]: Could you use a `SimpleIntegerProperty` here to remove this boilerplate code?

File: gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java [hunk 9]
```diff
@@ -51,72 +55,118 @@
...
+        try {
+            boolean fileIsUsable = playlistFile.exists();
+            if (!fileIsUsable){
+                fileIsUsable = playlistFile.createNewFile();
+            }
+
+            if ( fileIsUsable ){
+
+                OutputStream fileOutputStream = Files.newOutputStream(playlistFile.toPath(), StandardOpenOption.CREATE, APPEND);
+                BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fileOutputStream, StandardCharsets.UTF_8));
```
Comment (Tohaker) [inline gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java]: Preferably, the `OutputStream` and `BufferedWriter` should be in a try-with-resources block, so we don't have to explicitly close them and we take care of other potential memory leaks.

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java [hunk 10]
```diff
@@ -0,0 +1,241 @@
...
+        createTempTestDir();
+        MediaFileReader mfr = new MediaFileReader(mockGameContext) {
+            @Override
+            public File getMediaPlayerDirectory() {
+                return testDir;
+            }
+        };
+        assertNotNull(mfr);
+        assertTrue((new File(testDir, "playerList.csv")).exists());
+        FileUtils.deleteDirectoryRecursively(testDir);
```
Comment (Tohaker) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java]: You should move this to 
```java
@AfterEach
void teardown() {
        FileUtils.deleteDirectoryRecursively(testDir);
}
```

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java [hunk 11]
```diff
@@ -0,0 +1,241 @@
...
+    private static File testDir = new File("src/test/resources/testTestForMediaFileReader");
+
+    @BeforeEach
+    public void initMocks() {
+        MockitoAnnotations.initMocks(this);
+    }
+
+    @Test
+    void shouldCreatePlayerListCSVFileOnMediaFileReaderConstruct() {
+        createTempTestDir();
```
Comment (Tohaker) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java]: You should move this into the `@BeforeEach`.

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java [hunk 12]
```diff
@@ -0,0 +1,241 @@
...
+    void shouldReturnGoodValuesForFirstToDisplayFromSaveAfterAdd() throws IOException {
+        createTempTestDir();
+        File player = new File(testDir, "playerList.csv");
+        if (player.createNewFile() || player.exists()) {
+            OutputStream fileOutputStream = Files.newOutputStream(player.toPath(), StandardOpenOption.CREATE, APPEND);
+            BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fileOutputStream, StandardCharsets.UTF_8));
+            bw.write("URL,https://www.test1.fr/,test1,");
+            bw.write("\nMEDIA,images/black/black.jpg,test2,");
+            bw.close();
+        }
```
Comment (Tohaker) [inline gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java]: You could probably make a reusable method for creating these CSVs, that could take in a `List<String>` to write to the buffer. If we find other uses for it, we could even move it to `TestingUtils` in the `gazeplay` module.

File: gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java (hunk 10 above)
Comment (kuhlkrein) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java]: I think I tried but only the AfterAll was working, I'll check

Comment (Tohaker) [reply gazeplay-games/src/test/java/net/gazeplay/games/mediaPlayer/MediaFileReaderTest.java]: You may have to check the JUnit imports. Only the ones including `jupiter` will support `AfterEach`

**Comment by schwabdidier** [comment]
@Tohaker : can you perform the review ? Yann is very busy these days.

**Comment by Tohaker** [comment]
Sure, I'll take a look later today

File: gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java [hunk 13]
```diff
@@ -26,17 +26,19 @@
...
 
     MediaFileReader(IGameContext gameContext) {
         this.gameContext = gameContext;
         mediaList = new ArrayList<>();
-        index = -1;
-        playing = -1;
+        firstMediaDisplayedIndex = new SimpleIntegerProperty();
+        firstMediaDisplayedIndex.setValue(-1);
+        playingMediaIndex = new SimpleIntegerProperty();
+        playingMediaIndex.setValue(-1);
```
Comment (Tohaker) [inline gazeplay-games/src/main/java/net/gazeplay/games/mediaPlayer/MediaFileReader.java]: You can set the default value in the constructor of the `SimpleIntegerProperty`.
```suggestion
        playingMediaIndex = new SimpleIntegerProperty(-1);
```
